name: Check Bazel/Erlang.mk Equivalence (Matrix)
on:
  schedule:
  - cron: '0 2 * * *'
jobs:
  check-main:
    uses: ./.github/workflows/check-build-system-equivalence.yaml
    with:
      ref: main
      erlang_version: 26.0
      elixir_version: 1.15
      project_version: 3.13.0

  check-v3_12_x:
    uses: ./.github/workflows/check-build-system-equivalence.yaml
    with:
      ref: v3.12.x
      erlang_version: 26.0
      elixir_version: 1.15
      project_version: 3.12.0

  check-v3_11_x:
    uses: ./.github/workflows/check-build-system-equivalence.yaml
    with:
      ref: v3.11.x
      erlang_version: 26.0
      elixir_version: 1.15
      project_version: 3.11.0
